### ISSUE TITLE
Resize 窗口大小

### ISSUE THREAD

**Issue by tonyshield** [xjbeta/AppleDNS-GUI#1]
这个固定的窗口大小感觉用起来怪怪的，我稍微改了一下可以支持改变窗口大小了。要不要加上这个功能呢？
谢谢！

**Comment by xjbeta** [comment]
怎么说呢  个人认为这也不是经常使用的软件   基本要求就是: 能用就行

**Comment by xjbeta** [comment]
等我研究下怎么清理DNS缓存  把这个一起加进去
